package com.codex.ec.player.type;

public enum BowlingType {
	RIGHT_ARM_FAST,
	LEFT_ARM_FAST,
	RIGHT_ARM_FAST_MEDIUM,
	LEFT_ARM_FAST_MEDIUM,
	RIGHT_ARM_SEAM,
	LEFT_ARM_SEAM,
	RIGHT_ARM_OFF_BREAK,
	LEFT_ARM_OFF_BREAK,
	RIGHT_ARM_LEG_BREAK,
	LEFT_ARM_LEG_BREAK
}
